baseurl: /
languageCode: en-us
title: The website of Xingqi
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "study"
      url: "/study/"
      weight: 3
    - name: "life"
      url: "/life/"
      weight: 4
    - name: "Subscribe"
      url: "/index.xml"
      

params:
  description: "If one drinks cold and warm water, he knows that all kinds of sufferings can only be overcome by himself"
  footer: "&copy; [Xinqi]  @  2022 | [Github](https://github.com/zxingq)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true
